### ISSUE TITLE
Label consistency testing

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-flow#4]
Test to ensure all resource definitions have the correct label applied (i.e. don't let SensuFlow create resources that will then not be in scope for pruning). Fails if any definition is missing the configured label (default: `sensu.io/workflow`).

**Comment by jspaleta** [comment]
This is actually already in the sensuflow shell script. 

Linting to make sure the required label_key exists enforced as partof the sanity_checks.
setting DISABLE_SANITY_CHECK envvar will cause this to be skipped.
