### ISSUE TITLE
Documentation for running sensu-flow Docker container on its own

### ISSUE THREAD

**Issue by MichaelCharles** [sensu/sensu-flow#41]
I've been playing around with this locally.

Basically, you just need to run a command like this,

```
docker run -v $PWD/.sensu:/.sensu -e SENSU_API_KEY=550e8400-e29b-41d4-a716-446655440000 -e SENSU_API_URL=http://host.docker.internal:8080 -e VERBOSE=1 sensu/sensu-flow:0.6.0 --add-host host.docker.internal:host-gateway
```

And you can run the sensu-flow action against a local instance of the sensu backend.

If you want to run it against a sensu-backend that's been deployed, you'd do this,

```
docker run -v $PWD/.sensu:/.sensu -e SENSU_API_KEY=550e8400-e29b-41d4-a716-446655440000 -e SENSU_API_URL=https://sensu-api.example.com -e VERBOSE=1 sensu/sensu-flow:0.6.0
```

I'd like to write up some simple documentation explaining this, along with a brief explanation of the environment variables you can set for the [overview page](https://hub.docker.com/r/sensu/sensu-flow) on Docker Hub. Would that be allowed? If so, where/how would I go about doing that?

**Comment by jspaleta** [comment]
Adding as part of 0.7.0 release being prepped.
