### ISSUE TITLE
Documentation for running sensu-flow on Bitbucket pipelines.

### ISSUE THREAD

**Issue by MichaelCharles** [sensu/sensu-flow#42]
I'm using it in the way described in [this pull request](https://github.com/sensu/sensu-flow/pull/40) at work. If the documentation is acceptable, I'd really like to add it here.

This would be resolved by #40

**Comment by MichaelCharles** [comment]
I called my branch `js/add-bitbucket-docs` because I thought it was some kind of naming convention (after looking at the Gitlab request), but js stands for "Jef Spaleta," doesn't it?

**Comment by jspaleta** [comment]
it does indeed.

closing..as ive merged the pr.
