### ISSUE TITLE
Add a "Goals" section to README

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-flow#8]
Roadmap: 

- Add basic pre-flight tests 
- Ensure consistent labeling 
- Validate integrity of assets 
- Reference testing (if a check/handler refers to an asset, is the asset resource definition also present?)
- Actual resource type validation (and linting?)

**Comment by calebhailey** [comment]
Needed for linking from the announcement blog post.

**Comment by jspaleta** [comment]
Taken care of by PR #12
